[project]
name = "rag-proposal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-google-genai>=4.3.1",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.4.1",
    "python-dotenv>=1.2.2",
    "langchain-community>=0.4.1",
    "langchain-text-splitters>=1.0.0",
    "faiss-cpu>=1.9.0",
    "pypdf>=5.1.0",
    "fastapi>=0.118.0",
    "uvicorn[standard]>=0.34.0",
    "python-multipart>=0.0.20",
    "networkx>=3.4",
]
